### ISSUE TITLE
Week 3: Create a proposal

### ISSUE THREAD

**Issue by YingCG** [ITwhitecliffe/IT6041-Software-Project---Oct2022#1]
### Tasks 1 & 2: Team organization
- [ ] Team contract
- [ ] Selected collaboration tools

### Task 3 & 4: Requirements analysis
- [ ] The problem has been identified and matches
- [ ] User stories that reflect all the requirements for the proposed solution
- [ ] Client meeting minutes recorded
- [ ] Client feedback considered and addressed

### Task 5 Design Documentation
- [ ] What is the feature including in this project
- [ ] Feature to address clients need (functional or non-functional requirement)
- [ ] Wireframes and UI mockups

### Task 6: Planning process
- [ ]  tasks and timeline for each sprint
- [ ] Kanban board is set up with all design and implementation tasks
- [ ] Snapshot of Kanban board is posted in the Planning document and discussion board

### Task 5, 7, 8: Client and Lecture meeting
- [ ] Meeting minutes address the client feedback
- [ ] Meeting minutes show feedback considered and addressed for the design
- [ ] Meeting minutes show feedback considered and addressed for final proposal
- [ ] Arranged a meeting with the lecture discussed client’ feedback.
