### ISSUE TITLE
Week 1 & Week 4 : Personal Documentation

### ISSUE THREAD

**Issue by YingCG** [ITwhitecliffe/IT6041-Software-Project---Oct2022#11]
## Week 1
- [ ] Get use to github: https://www.notion.so/zarkom/Introduction-to-Git-ac396a0697704709a12b6a0e545db049
- [ ] Setup a github pages as your document
**Basic html page:** https://pages.github.com/

Personally I encourage you to do your documentation as personal reflection here instead using our usual word document, I believe this help you to stand out for your knowledge of a experience from your Business analysis skill + your coding skills.

Github cheatsheet - https://education.github.com/git-cheat-sheet-education.pdf

### Task 10: Individual reflective journal
Reflective journal entries fully explained:
- [ ] Tasks completed
- [ ] One design feature
- [ ] Team work reflection
- [ ] Explanation of how the project addresses the sustainability, equity, social or contemporary cultural issues shows a thorough understanding

## More advance stuff
**How to deploy React App to GitHub Pages**
https://dev.to/yuribenjamin/how-to-deploy-react-app-in-github-pages-2a1f

**To host your Django Project**
https://docs.djangoproject.com/en/1.8/howto/deployment/

**Example for documentation to include what we have learned:**
https://mahsakeyhani.com/memento.html
