### ISSUE TITLE
Week 4 : Execute the proposed solution.

### ISSUE THREAD

**Issue by YingCG** [ITwhitecliffe/IT6041-Software-Project---Oct2022#2]
This will involve implementing specific features in each of the applications, project management, working in multiple development environments, and arranging regular client meetings. 

### Task 1: Project Management 
- [ ]  planning session, sprint and retrospective each week
- [ ] the Kanban board and shots should be taken before and after 
the meeting 
- [ ] The Scrum Master takes meeting notes. 

### Task 2: Software Development 
- [ ]  Your development environment 
- [ ] Create user interface
- [ ] Setup user navigation 
- [ ] Set up data access 
- [ ] Add functionality 
- [ ] Application test and the testing feedback

### Task 3: Application Security 
- [ ] User authentication and authorisation

### Task 4: Industry engagement 
- [ ] Feedback on future improvements from professional

### Task 5: Testing 
- [ ] Overall test plan  
- [ ] UAT test cases  
- [ ] Usability/Playability test cases 
- [ ] Cross-browser test cases (if applicable) 

### Task 6: Client Feedback 
- [ ] client’s expectations are met
- [ ] client requests have been improved

### Task 7: Checkpoint(s) with lecturer
- [ ] present your progress as individual
- [ ] present your progress as group

### Task 8: Individual Reflective Journal 
1. A reflection on the development process for each sprint: 
- [ ] What was the most valuable lesson learnt this sprint? 
- [ ] What were the frustrations? 
2. A summary of your personal contributions:  
- [ ] Your team role. 
- [ ] The tasks you completed. 
3. One implementation commentary:  
- [ ] Explain one implementation feature you contributed to. Include evidence of your 
contribution. 
4. One testing commentary:  
- [ ] Explain one test session you performed, and include the test plan, test results and bugs 
found. 
5. A reflection on the teamwork: 
- [ ] What went well 
- [ ] What issues were met and how they were resolved 

### Task 9: Peer evaluation and reflection 
- [ ] Team Member Evaluation form for each members including yourself
- [ ] Thoughtfully and constructively comments
