### ISSUE TITLE
Week 9: Present the solution.

### ISSUE THREAD

**Issue by YingCG** [ITwhitecliffe/IT6041-Software-Project---Oct2022#3]
Present the solution at exhibition day

### Task 1: Presentation Preparation

- [ ] Title and overview. 
- [ ] Design decisions you made as a team. 
- [ ] Some challenges you faced in the design, execution and project time management processes. 
- [ ] Any changes you made to the planning and/or design during the development process.  What were those changes and why were they necessary (provide some examples)? 
- [ ] Schedule a presentation time with your tutor. 

### Task 2: Presentation 

- [ ] Ensure your applications can run so you can properly demonstrate your solution.  
- [ ] Deliver the presentation to your peers and tutors. Each team member should present some of the solution’s functionality. 
- [ ] Be ready to answer questions on the development process, teamwork and the sustainability, equity, social or contemporary cultural issue your solution addresses.  

### Individual reflection journal  
- [ ] A summary of your personal contributions:  
- [ ] The tasks you completed 
- [ ] A reflection on the teamwork: 
- [ ] What went well 
- [ ] What issues were met and how they were resolved
